### ISSUE TITLE
Integrate the salesforce code to our api

### ISSUE THREAD

**Issue by Spurrya** [Spurrya/Calfit#11]

**Comment by Spurrya** [comment]
Code from shebin for that is available here https://github.com/shebinmathew/node-js-sample/blob/master/index.js . Please note that this code did not use the parameter "Last time reminder was shown", because the specification did not include that at that time. 

Please feel free to ask if something is unclear.

**Comment by bhaanu77** [comment]
@Spurrya I am not sure if you misunderstood my comment you copy pasted above; in that comment I was saying that the code in  https://github.com/shebinmathew/node-js-sample/blob/master/index.js contains the logic to decide whether a reminder should be sent to user.

Salesforce code is not yet in github to my knowledge and I will ask him to send that
